import { CODES, HTTP_STATUS_MAPPINGS } from "./constants";
import {
    getStatusCode,
    getStatusName,
    getStatusDescription,
    isInformational,
    isSuccess,
    isRedirectional,
    isClientError,
    isServerError,
    getInformationalCodes,
    getSuccessCodes,
    getRedirectionalCodes,
    getClientErrorCodes,
    getServerErrorCodes,
    isValidStatusCode,
} from "./utils";

export {
    CODES,
    getStatusCode,
    getStatusName,
    getStatusDescription,
    isInformational,
    isSuccess,
    isRedirectional,
    isClientError,
    isServerError,
    getInformationalCodes,
    getSuccessCodes,
    getRedirectionalCodes,
    getClientErrorCodes,
    getServerErrorCodes,
    isValidStatusCode,
};

export const CONTINUE = HTTP_STATUS_MAPPINGS.CONTINUE.code;
export const SWITCHING_PROTOCOLS =
    HTTP_STATUS_MAPPINGS.SWITCHING_PROTOCOLS.code;
export const PROCESSING = HTTP_STATUS_MAPPINGS.PROCESSING.code;
export const EARLY_HINTS = HTTP_STATUS_MAPPINGS.EARLY_HINTS.code;
export const TOO_LONG = HTTP_STATUS_MAPPINGS.TOO_LONG.code;
export const OK = HTTP_STATUS_MAPPINGS.OK.code;
export const CREATED = HTTP_STATUS_MAPPINGS.CREATED.code;
export const ACCEPTED = HTTP_STATUS_MAPPINGS.ACCEPTED.code;
export const NON_AUTHORITATIVE_INFORMATION =
    HTTP_STATUS_MAPPINGS.NON_AUTHORITATIVE_INFORMATION.code;
export const NO_CONTENT = HTTP_STATUS_MAPPINGS.NO_CONTENT.code;
export const RESET_CONTENT = HTTP_STATUS_MAPPINGS.RESET_CONTENT.code;
export const PARTIAL_CONTENT = HTTP_STATUS_MAPPINGS.PARTIAL_CONTENT.code;
export const MULTI_STATUS = HTTP_STATUS_MAPPINGS.MULTI_STATUS.code;
export const ALREADY_REPORTED = HTTP_STATUS_MAPPINGS.ALREADY_REPORTED.code;
export const IM_USED = HTTP_STATUS_MAPPINGS.IM_USED.code;
export const MULTIPLE_CHOICES = HTTP_STATUS_MAPPINGS.MULTIPLE_CHOICES.code;
export const MOVED_PERMANENTLY = HTTP_STATUS_MAPPINGS.MOVED_PERMANENTLY.code;
export const MOVED_TEMPORARILY = HTTP_STATUS_MAPPINGS.MOVED_TEMPORARILY.code;
export const SEE_OTHER = HTTP_STATUS_MAPPINGS.SEE_OTHER.code;
export const NOT_MODIFIED = HTTP_STATUS_MAPPINGS.NOT_MODIFIED.code;
export const USE_PROXY = HTTP_STATUS_MAPPINGS.USE_PROXY.code;
export const SWITCH_PROXY = HTTP_STATUS_MAPPINGS.SWITCH_PROXY.code;
export const TEMPORARY_REDIRECT = HTTP_STATUS_MAPPINGS.TEMPORARY_REDIRECT.code;
export const PERMANENT_REDIRECT = HTTP_STATUS_MAPPINGS.PERMANENT_REDIRECT.code;
export const BAD_REQUEST = HTTP_STATUS_MAPPINGS.BAD_REQUEST.code;
export const UNAUTHORIZED = HTTP_STATUS_MAPPINGS.UNAUTHORIZED.code;
export const PAYMENT_REQUIRED = HTTP_STATUS_MAPPINGS.PAYMENT_REQUIRED.code;
export const FORBIDDEN = HTTP_STATUS_MAPPINGS.FORBIDDEN.code;
export const NOT_FOUND = HTTP_STATUS_MAPPINGS.NOT_FOUND.code;
export const METHOD_NOT_ALLOWED = HTTP_STATUS_MAPPINGS.METHOD_NOT_ALLOWED.code;
export const NOT_ACCEPTABLE = HTTP_STATUS_MAPPINGS.NOT_ACCEPTABLE.code;
export const PROXY_AUTHENTICATION_REQUIRED =
    HTTP_STATUS_MAPPINGS.PROXY_AUTHENTICATION_REQUIRED.code;
export const REQUEST_TIMEOUT = HTTP_STATUS_MAPPINGS.REQUEST_TIMEOUT.code;
export const CONFLICT = HTTP_STATUS_MAPPINGS.CONFLICT.code;
export const GONE = HTTP_STATUS_MAPPINGS.GONE.code;
export const LENGTH_REQUIRED = HTTP_STATUS_MAPPINGS.LENGTH_REQUIRED.code;
export const PRECONDITION_FAILED =
    HTTP_STATUS_MAPPINGS.PRECONDITION_FAILED.code;
export const REQUEST_TOO_LONG = HTTP_STATUS_MAPPINGS.REQUEST_TOO_LONG.code;
export const REQUEST_URI_TOO_LONG =
    HTTP_STATUS_MAPPINGS.REQUEST_URI_TOO_LONG.code;
export const UNSUPPORTED_MEDIA_TYPE =
    HTTP_STATUS_MAPPINGS.UNSUPPORTED_MEDIA_TYPE.code;
export const REQUESTED_RANGE_NOT_SATISFIABLE =
    HTTP_STATUS_MAPPINGS.REQUESTED_RANGE_NOT_SATISFIABLE.code;
export const EXPECTATION_FAILED = HTTP_STATUS_MAPPINGS.EXPECTATION_FAILED.code;
export const IM_A_TEAPOT = HTTP_STATUS_MAPPINGS.IM_A_TEAPOT.code;
export const INSUFFICIENT_SPACE_ON_RESOURCE =
    HTTP_STATUS_MAPPINGS.INSUFFICIENT_SPACE_ON_RESOURCE.code;
export const METHOD_FAILURE = HTTP_STATUS_MAPPINGS.METHOD_FAILURE.code;
export const MISDIRECTED_REQUEST =
    HTTP_STATUS_MAPPINGS.MISDIRECTED_REQUEST.code;
export const UNPROCESSABLE_ENTITY =
    HTTP_STATUS_MAPPINGS.UNPROCESSABLE_ENTITY.code;
export const LOCKED = HTTP_STATUS_MAPPINGS.LOCKED.code;
export const FAILED_DEPENDENCY = HTTP_STATUS_MAPPINGS.FAILED_DEPENDENCY.code;
export const TOO_EARLY = HTTP_STATUS_MAPPINGS.TOO_EARLY.code;
export const UPGRADE_REQUIRED = HTTP_STATUS_MAPPINGS.UPGRADE_REQUIRED.code;
export const PRECONDITION_REQUIRED =
    HTTP_STATUS_MAPPINGS.PRECONDITION_REQUIRED.code;
export const TOO_MANY_REQUESTS = HTTP_STATUS_MAPPINGS.TOO_MANY_REQUESTS.code;
export const REQUEST_HEADER_FIELDS_TOO_LARGE =
    HTTP_STATUS_MAPPINGS.REQUEST_HEADER_FIELDS_TOO_LARGE.code;
export const UNAVAILABLE_FOR_LEGAL_REASONS =
    HTTP_STATUS_MAPPINGS.UNAVAILABLE_FOR_LEGAL_REASONS.code;
export const INTERNAL_SERVER_ERROR =
    HTTP_STATUS_MAPPINGS.INTERNAL_SERVER_ERROR.code;
export const NOT_IMPLEMENTED = HTTP_STATUS_MAPPINGS.NOT_IMPLEMENTED.code;
export const BAD_GATEWAY = HTTP_STATUS_MAPPINGS.BAD_GATEWAY.code;
export const SERVICE_UNAVAILABLE =
    HTTP_STATUS_MAPPINGS.SERVICE_UNAVAILABLE.code;
export const GATEWAY_TIMEOUT = HTTP_STATUS_MAPPINGS.GATEWAY_TIMEOUT.code;
export const HTTP_VERSION_NOT_SUPPORTED =
    HTTP_STATUS_MAPPINGS.HTTP_VERSION_NOT_SUPPORTED.code;
export const VARIANT_ALSO_NEGOTIATES =
    HTTP_STATUS_MAPPINGS.VARIANT_ALSO_NEGOTIATES.code;
export const INSUFFICIENT_STORAGE =
    HTTP_STATUS_MAPPINGS.INSUFFICIENT_STORAGE.code;
export const LOOP_DETECTED = HTTP_STATUS_MAPPINGS.LOOP_DETECTED.code;
export const NOT_EXTENDED = HTTP_STATUS_MAPPINGS.NOT_EXTENDED.code;
export const NETWORK_AUTHENTICATION_REQUIRED =
    HTTP_STATUS_MAPPINGS.NETWORK_AUTHENTICATION_REQUIRED.code;

const EXPORTS = {
    CODES,
    getStatusCode,
    getStatusName,
    getStatusDescription,
    isInformational,
    isSuccess,
    isRedirectional,
    isClientError,
    isServerError,
    getInformationalCodes,
    getSuccessCodes,
    getRedirectionalCodes,
    getClientErrorCodes,
    getServerErrorCodes,
    isValidStatusCode,
    CONTINUE,
    SWITCHING_PROTOCOLS,
    PROCESSING,
    EARLY_HINTS,
    TOO_LONG,
    OK,
    CREATED,
    ACCEPTED,
    NON_AUTHORITATIVE_INFORMATION,
    NO_CONTENT,
    RESET_CONTENT,
    PARTIAL_CONTENT,
    MULTI_STATUS,
    ALREADY_REPORTED,
    IM_USED,
    MULTIPLE_CHOICES,
    MOVED_PERMANENTLY,
    MOVED_TEMPORARILY,
    SEE_OTHER,
    NOT_MODIFIED,
    USE_PROXY,
    SWITCH_PROXY,
    TEMPORARY_REDIRECT,
    PERMANENT_REDIRECT,
    BAD_REQUEST,
    UNAUTHORIZED,
    PAYMENT_REQUIRED,
    FORBIDDEN,
    NOT_FOUND,
    METHOD_NOT_ALLOWED,
    NOT_ACCEPTABLE,
    PROXY_AUTHENTICATION_REQUIRED,
    REQUEST_TIMEOUT,
    CONFLICT,
    GONE,
    LENGTH_REQUIRED,
    PRECONDITION_FAILED,
    REQUEST_TOO_LONG,
    REQUEST_URI_TOO_LONG,
    UNSUPPORTED_MEDIA_TYPE,
    REQUESTED_RANGE_NOT_SATISFIABLE,
    EXPECTATION_FAILED,
    IM_A_TEAPOT,
    INSUFFICIENT_SPACE_ON_RESOURCE,
    METHOD_FAILURE,
    MISDIRECTED_REQUEST,
    UNPROCESSABLE_ENTITY,
    LOCKED,
    FAILED_DEPENDENCY,
    TOO_EARLY,
    UPGRADE_REQUIRED,
    PRECONDITION_REQUIRED,
    TOO_MANY_REQUESTS,
    REQUEST_HEADER_FIELDS_TOO_LARGE,
    UNAVAILABLE_FOR_LEGAL_REASONS,
    INTERNAL_SERVER_ERROR,
    NOT_IMPLEMENTED,
    BAD_GATEWAY,
    SERVICE_UNAVAILABLE,
    GATEWAY_TIMEOUT,
    HTTP_VERSION_NOT_SUPPORTED,
    VARIANT_ALSO_NEGOTIATES,
    INSUFFICIENT_STORAGE,
    LOOP_DETECTED,
    NOT_EXTENDED,
    NETWORK_AUTHENTICATION_REQUIRED,
};
module.exports = EXPORTS;
